#define MAINPREFIX x
#define PREFIX TMF

#define MAJOR 1
#define MINOR 0
#define PATCH 0
#define BUILD 5

#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD

#define REQUIRED_VERSION 1.56
